# This file is auto-generated by Chargebee.
# For more information on how to make changes to this file, please see the README.
# Reach out to dx@chargebee.com for any questions.
# Copyright 2026 Chargebee Inc.

module ChargeBee
  module Telemetry
    # Context passed to TelemetryAdapter#on_request_start.
    class RequestTelemetryContext
      attr_reader :span_name, :resource, :operation, :http_method, :http_url, :server_address,
                  :chargebee_site, :chargebee_api_version, :sdk_name, :sdk_version, :start_attributes

      def initialize(span_name:, resource:, operation:, http_method:, http_url:, server_address:,
                     chargebee_site:, chargebee_api_version:, sdk_name:, sdk_version:, start_attributes:)
        @span_name = span_name
        @resource = resource
        @operation = operation
        @http_method = http_method
        @http_url = http_url
        @server_address = server_address
        @chargebee_site = chargebee_site
        @chargebee_api_version = chargebee_api_version
        @sdk_name = sdk_name
        @sdk_version = sdk_version
        @start_attributes = start_attributes.freeze
      end
    end
  end
end
