# This file is auto-generated by Chargebee.
# For more information on how to make changes to this file, please see the README.
# Reach out to dx@chargebee.com for any questions.
# Copyright 2026 Chargebee Inc.

module ChargeBee
  module Telemetry
    # Error details attached to RequestTelemetryResult on failed requests.
    class RequestTelemetryError
      attr_reader :message, :chargebee_error_code, :chargebee_api_error_type, :chargebee_error_param

      def initialize(message:, chargebee_error_code: nil, chargebee_api_error_type: nil, chargebee_error_param: nil)
        @message = message
        @chargebee_error_code = chargebee_error_code
        @chargebee_api_error_type = chargebee_api_error_type
        @chargebee_error_param = chargebee_error_param
      end
    end
  end
end
