# This file is auto-generated by Chargebee.
# For more information on how to make changes to this file, please see the README.
# Reach out to dx@chargebee.com for any questions.
# Copyright 2026 Chargebee Inc.

module ChargeBee
  module Telemetry
    # Optional telemetry adapter for observability integrations (e.g. OpenTelemetry).
    #
    # When not configured, the SDK skips all telemetry work — zero overhead. The SDK stores the
    # adapter by reference and never clones or deep-copies it.
    #
    # Implementations may inject W3C trace context headers (traceparent, tracestate) into
    # request_headers during on_request_start.
    module TelemetryAdapter
      # Called once per SDK API call before the request is sent (including before retries).
      #
      # context contains prebuilt start attributes. request_headers is a mutable map for trace propagation.
      # Returns an opaque handle passed back to on_request_end, or nil if span creation was skipped.
      def on_request_start(context, request_headers)
        raise NotImplementedError
      end

      # Called once per SDK API call after the final response or terminal failure.
      #
      # handle is the value returned from on_request_start and may be nil. result contains prebuilt end attributes.
      def on_request_end(handle, result)
        raise NotImplementedError
      end
    end
  end
end
