# This file is auto-generated by Chargebee.
# For more information on how to make changes to this file, please see the README.
# Reach out to dx@chargebee.com for any questions.
# Copyright 2026 Chargebee Inc.

module ChargeBee
  module Telemetry
    # Span attribute keys shared across Chargebee SDKs.
    module TelemetryAttributeKeys
      SDK_NAME = 'chargebee-ruby'.freeze
      TELEMETRY_SPAN_NAME_PREFIX = 'chargebee'.freeze

      HTTP_REQUEST_HEADER_ATTRIBUTE_PREFIX = 'http.request.header.'.freeze
      CHARGEBEE_TELEMETRY_HEADER_PREFIX = 'chargebee-'.freeze
      CHARGEBEE_TELEMETRY_HEADER_EXCLUDE_PREFIX = 'chargebee-request-origin-'.freeze

      URL_FULL = 'url.full'.freeze
      HTTP_REQUEST_METHOD = 'http.request.method'.freeze
      HTTP_RESPONSE_STATUS_CODE = 'http.response.status_code'.freeze
      SERVER_ADDRESS = 'server.address'.freeze
      ERROR_TYPE = 'error.type'.freeze
      CHARGEBEE_SITE = 'chargebee.site'.freeze
      CHARGEBEE_API_VERSION = 'chargebee.api_version'.freeze
      CHARGEBEE_RESOURCE = 'chargebee.resource'.freeze
      CHARGEBEE_OPERATION = 'chargebee.operation'.freeze
      CHARGEBEE_SDK_NAME = 'chargebee.sdk.name'.freeze
      CHARGEBEE_SDK_VERSION = 'chargebee.sdk.version'.freeze
      CHARGEBEE_ERROR_CODE = 'chargebee.error.code'.freeze
      CHARGEBEE_ERROR_TYPE = 'chargebee.error.type'.freeze
      CHARGEBEE_ERROR_PARAM = 'chargebee.error.param'.freeze
    end
  end
end
