# This file is auto-generated by Chargebee.
# For more information on how to make changes to this file, please see the README.
# Reach out to dx@chargebee.com for any questions.
# Copyright 2026 Chargebee Inc.

module ChargeBee
  module Telemetry
    # Helpers for building standardized Chargebee telemetry context and results.
    class TelemetrySupport
      class << self
        def build_span_name(resource, operation)
          "#{TelemetryAttributeKeys::TELEMETRY_SPAN_NAME_PREFIX}.#{resource}.#{operation}"
        end

        def resolve_chargebee_api_version(api_path)
          api_path == '/api/v1' ? 'v1' : 'v2'
        end

        def build_request_start_span_attributes(resource, operation, http_method, http_url, server_address,
                                                chargebee_site, chargebee_api_version, sdk_version)
          {
            TelemetryAttributeKeys::URL_FULL => http_url,
            TelemetryAttributeKeys::HTTP_REQUEST_METHOD => http_method,
            TelemetryAttributeKeys::SERVER_ADDRESS => server_address,
            TelemetryAttributeKeys::CHARGEBEE_SITE => chargebee_site,
            TelemetryAttributeKeys::CHARGEBEE_API_VERSION => chargebee_api_version,
            TelemetryAttributeKeys::CHARGEBEE_RESOURCE => resource,
            TelemetryAttributeKeys::CHARGEBEE_OPERATION => operation,
            TelemetryAttributeKeys::CHARGEBEE_SDK_NAME => TelemetryAttributeKeys::SDK_NAME,
            TelemetryAttributeKeys::CHARGEBEE_SDK_VERSION => sdk_version,
          }
        end

        def build_request_end_span_attributes(http_status_code, error)
          attributes = {
            TelemetryAttributeKeys::HTTP_RESPONSE_STATUS_CODE => http_status_code,
          }

          if error
            attributes[TelemetryAttributeKeys::ERROR_TYPE] = http_status_code.to_s
            attributes[TelemetryAttributeKeys::CHARGEBEE_ERROR_CODE] = error.chargebee_error_code if error.chargebee_error_code
            attributes[TelemetryAttributeKeys::CHARGEBEE_ERROR_TYPE] = error.chargebee_api_error_type if error.chargebee_api_error_type
            attributes[TelemetryAttributeKeys::CHARGEBEE_ERROR_PARAM] = error.chargebee_error_param if error.chargebee_error_param
          end

          attributes
        end

        def build_request_telemetry_context(resource, operation, http_method, http_url, server_address,
                                            chargebee_site, chargebee_api_version, sdk_version)
          RequestTelemetryContext.new(
            span_name: build_span_name(resource, operation),
            resource: resource,
            operation: operation,
            http_method: http_method,
            http_url: http_url,
            server_address: server_address,
            chargebee_site: chargebee_site,
            chargebee_api_version: chargebee_api_version,
            sdk_name: TelemetryAttributeKeys::SDK_NAME,
            sdk_version: sdk_version,
            start_attributes: build_request_start_span_attributes(
              resource, operation, http_method, http_url, server_address, chargebee_site, chargebee_api_version, sdk_version
            ),
          )
        end

        def build_request_telemetry_result(http_status_code, duration_ms, error)
          RequestTelemetryResult.new(
            http_status_code: http_status_code,
            duration_ms: duration_ms,
            error: error,
            end_attributes: build_request_end_span_attributes(http_status_code, error),
          )
        end

        def extract_request_telemetry_error(err)
          return nil if err.nil?

          message = err.message.to_s
          message = 'Chargebee API request failed' if message.empty?

          if err.is_a?(ChargeBee::APIError)
            return RequestTelemetryError.new(
              message: message,
              chargebee_error_code: err.api_error_code,
              chargebee_api_error_type: err.type.to_s,
              chargebee_error_param: err.param,
            )
          end

          RequestTelemetryError.new(message: message)
        end

        def extract_http_status_code(err)
          return err.http_status_code if err.is_a?(ChargeBee::APIError)

          nil
        end
      end
    end
  end
end
